# Присоединяйтесь к нам в Discord-сервер: https://dsc.gg/amazingplugins

# Тип форматирования сообщений.
#: LEGACY - Классика (&a, &#rrggbb)
#: MINI_MESSAGE - <цвет> (1.18+)
# Подробнее о MiniMessage: https://docs.papermc.io/adventure/minimessage/format/
serializer: LEGACY
# Оповещать при выходе новых версий (рекомендуется)
notify-updates: true

# Настройки базы данных.
database-settings:
  type: sqlite # sqlite / mysql
  sqlite: # настройки только для sqlite
    file-path: "data.db"
  mysql: # настройки только для mysql
    host: "127.0.0.1"
    port: 3306
    database: "playerthemes"
    username: "root"
    password: ""
    # Параметры подключения к внешней базе данных.
    # Лучше не изменяйте, если не разбираетесь в этом.
    arguments: "?useSSL=false&autoReconnect=true&characterEncoding=utf8"
  # Настройки пула HikariCP.
  # Можете добавлять любые параметры, поддерживаемым им.
  pool-settings:
    maximum-pool-size: 10
    connection-timeout: 5000
    max-lifetime: 1800000
  # Настройки Redis для мультисерверности.
  # Используется в добавок с MySQL.
  redis:
    enabled: false
    server-id: 'grief-1'
    channel: 'playerthemes:sync'
    connection:
      host: "127.0.0.1"
      port: 6379
      username: ""
      password: ""
      database: 0

# Настройки команды выбора темы.
command-settings:
  main-command: "themes"
  aliases:
    - "design"
    - "customization"
    - "custom"
  select:
    command-cooldown: 5000 # время кд в миллисекундах. чтобы отключить - установите значение 0
    cooldown-bypass: true # байпас кд игрокам с правом playerthemes.cooldown.bypass
  select-other:
    command-cooldown: 0 # время кд в миллисекундах. чтобы отключить - установите значение 0
    cooldown-bypass: true # байпас кд игрокам с правом playerthemes.cooldown.bypass

# Сообщения плагина.
messages:
  prefix: "&6[★] &7»&f"
  no-permission: "%prefix% У вас &cнет полномочий&f, чтобы &6выполнить&f данное действие."
  only-players: "%prefix% Данную команду могут выполнять только игроки."
  cooldown: "%prefix% Подождите &a%time% сек.&f перед &6следующим использованием&f команды."
  admin:
    reloaded: "%prefix% Плагин &aуспешно&f перезагружен!"
    help: |-
      &6[★] Помощь по Плагину:
      &8- &e/pth reload &8» &7Перезагрузить плагин.
  theme:
    not-found: "%prefix% Тема &c%theme%&f не найдена."
    no-permission: "%prefix% Вы &cне можете&f использовать тему &6%theme%&f."
    installed: "%prefix% Вы &aуспешно&f установили тему оформления &6%theme%&f."
    installed-player: "%prefix% Тема &a%theme%&f успешно установлена для игрока &6%player%&f."
    reset-success: "%prefix% Ваше оформление было &aуспешно&f сброшено до &6стандартного&f."
    reset-success-player: "%prefix% Оформление игрока &6%player%&f успешно сброшено."
    help: |-
      &6[★] Помощь по Кастомизации:
      &8- &e/themes [тема] &8» &7Выбрать тему оформления.
      &8- &e/themes reset &8» &7Сбросить текущую тему до стандартной.

config-version: 2 # Не изменяйте данный параметр!